### ISSUE TITLE
fix logo zIndex to make sure tooltips can be closed

### ISSUE THREAD

**Issue by igorgaelzer** [spiermar/yakinaround.com#10]
![captura de tela 2015-06-14 as 11 17 41](https://cloud.githubusercontent.com/assets/7076656/8148889/0f8acb10-1287-11e5-8ba5-c1088ce1e070.png)

When I try to close the video preview it thinks I'm clicking on the Yakin Around logo and takes me to our main website. Tried clicking out of the preview box to close it also clicking on the video icon again but it just opened another preview box.

**Comment by spiermar** [comment]
Notice that this could be an issue. The problem is the zIndex of the logo and the popup. Basically the logo is in front of the popup and there is a link in it.

**Comment by spiermar** [comment]
So, this can't be done the way it's set up right now. The logo overlay is a map control, and by definition controls take precedence over any other item in the map. I'll try to convert it to an image overlay.

**Comment by spiermar** [comment]
The image overlay has a few restrictions. Besides being behind other stuff, it has a fixed map position, meaning that it will move with the map. Not a big fan of this option, but I managed to fix the worst part of the problem. The link was set to the whole div that covered the top part of the map, that's why nothing could be clicked there. Fix that and now only the logo is clickable. That should solve the main hurdle.

**Comment by igorgaelzer** [comment]
True, there was a big space around the logo that was being considered a link. Much better now.
